#!/usr/bin/env tsx
import { existsSync, readFileSync, readdirSync, writeFileSync, statSync } from "node:fs";
import { join, basename, extname } from "node:path";

const ROOT = process.cwd();
const PACK = process.env.PACK_DIR ? process.env.PACK_DIR : join(ROOT, "pack");
const OUT = process.env.OUT_PATH ? process.env.OUT_PATH : join(ROOT, "lib/_pack.ts");

function fail(msg: string): never {
  console.error(`bundle-pack: ${msg}`);
  process.exit(1);
}

function readJson(filePath: string): unknown {
  try {
    return JSON.parse(readFileSync(filePath, "utf-8"));
  } catch (e) {
    fail(`malformed JSON in ${filePath}: ${(e as Error).message}`);
  }
}

function readDirJson(dir: string): Record<string, unknown> {
  if (!existsSync(dir)) return {};
  const out: Record<string, unknown> = {};
  for (const f of readdirSync(dir)) {
    if (extname(f) !== ".json") continue;
    const name = basename(f, ".json");
    out[name] = readJson(join(dir, f));
  }
  return out;
}

function readDirText(dir: string, ext: string): Record<string, string> {
  if (!existsSync(dir)) return {};
  const out: Record<string, string> = {};
  for (const f of readdirSync(dir)) {
    if (extname(f) !== ext) continue;
    const name = basename(f, ext);
    out[name] = readFileSync(join(dir, f), "utf-8");
  }
  return out;
}

if (!existsSync(PACK)) {
  fail(
    "no pack found at ./pack — copy a starter pack from ./packs/ (e.g. `cp -R packs/internal-ops/. pack/`) or build your own.",
  );
}

const REQUIRED = ["manifest.json", "briefing.schema.json", "cycles.json"];
for (const f of REQUIRED) {
  if (!existsSync(join(PACK, f))) {
    fail(`pack is missing required file: ${f} (expected at ${join(PACK, f)})`);
  }
}

const manifest = readJson(join(PACK, "manifest.json"));
const briefingSchema = readJson(join(PACK, "briefing.schema.json"));
const sectionSchemas = readDirJson(join(PACK, "sections/schema"));
const cycles = readJson(join(PACK, "cycles.json"));
const confidence = existsSync(join(PACK, "CONFIDENCE.json"))
  ? readJson(join(PACK, "CONFIDENCE.json"))
  : {};

const briefingPath = join(PACK, "briefing.json");
const briefingExamplePath = join(PACK, "briefing.example.json");
const briefing = existsSync(briefingPath)
  ? readJson(briefingPath)
  : existsSync(briefingExamplePath)
  ? readJson(briefingExamplePath)
  : null;

if (briefing === null) {
  fail("no briefing.json or briefing.example.json found in pack/");
}

const sectionsDataDir = join(PACK, "sections");
const sectionExamplesDir = join(PACK, "sections");
let sections: Record<string, unknown> = {};
if (existsSync(sectionsDataDir) && statSync(sectionsDataDir).isDirectory()) {
  for (const f of readdirSync(sectionsDataDir)) {
    if (!f.endsWith(".json") || f.endsWith(".example.json")) continue;
    if (f === "schema") continue;
    const name = basename(f, ".json");
    sections[name] = readJson(join(sectionsDataDir, f));
  }
  if (Object.keys(sections).length === 0 && existsSync(sectionExamplesDir)) {
    for (const f of readdirSync(sectionExamplesDir)) {
      if (!f.endsWith(".example.json")) continue;
      const name = f.replace(/\.example\.json$/, "");
      sections[name] = readJson(join(sectionExamplesDir, f));
    }
  }
}

const renderHints = readDirText(join(PACK, "render-hints"), ".md");

const out = `// AUTO-GENERATED by scripts/bundle-pack.ts — do not edit.
// Regenerated on every \`npm run bundle-pack\`.

export const MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;
export const BRIEFING_SCHEMA = ${JSON.stringify(briefingSchema, null, 2)};
export const SECTION_SCHEMAS: Record<string, unknown> = ${JSON.stringify(sectionSchemas, null, 2)};
export const CYCLES = ${JSON.stringify(cycles, null, 2)};
export const CONFIDENCE = ${JSON.stringify(confidence, null, 2)};
export const BRIEFING: Record<string, any> = ${JSON.stringify(briefing, null, 2)};
export const SECTIONS: Record<string, any> = ${JSON.stringify(sections, null, 2)};
export const RENDER_HINTS: Record<string, string> = ${JSON.stringify(renderHints, null, 2)};
`;

writeFileSync(OUT, out);
console.log(`bundle-pack: wrote ${OUT}`);
